---
- name: create build directory
  file: dest={{ src_build_dir }} state=directory

- name: clone etcd
  git: repo={{ etcd_git_repo }} version={{ etcd_version }} dest={{ etcd_build_dir }}

- name: build etcd exec
  shell: ./build chdir={{ etcd_build_dir }}

- name: delete binaries if already there
  file: dest={{ etcd_bin_dir }}/{{ item }} state=absent
  with_items:
    - etcd

- name: copy binaries to files directory
  copy: src={{ etcd_build_dir }}/bin/{{ item }} dest={{ etcd_bin_dir }}/{{ item }} mode=0755
  with_items:
    - etcd

- name: clean temp files
  file: dest={{ src_build_dir }} state=absent
